example
exampleTree

	^'Example' -> {  
		
		'' -> {  
			'Repl' -> {  } @ 'repl'.
			'Class' -> {  } @ 'class'
		} @ 'gray'.
		
		'GrammarTraits' -> {  
			'Repl' -> {  } @ 'repl'.
			'Class' -> {  } @ 'class'		
		} @ 'project'.
		
		'MOODs' -> {  
			'Repl' -> {  } @ 'repl'.
			'Class' -> {  } @ 'class'
		} @ 'project'.
	
		'Lise' -> {  
			'Repl' -> {  } @ 'repl'.
			'Class' -> {  } @ 'class'	
		} @ 'project'.
	
	}