baselines
packagesAndBaselinesFor: spec
	^ spec
		project: 'Roassal2'
			with: [ spec
				className: 'ConfigurationOfRoassal2';
				file: 'ConfigurationOfRoassal2';
				version: '1.59';
				repository: 'http://www.smalltalkhub.com/mc/ObjectProfile/Roassal2/main' ];
				package: 'Lands-MOGs-Gray-Lexing';
		package: 'Lands-MOGs-Gray';
		package: 'Lands-ToolCompatibility';
		package: 'Lands-Parsers';
		package: 'Lands-GTraits';
		package: 'Lands-LanguageClasses';
		package: 'Lands-GTraits-Parsers';
		package: 'Lands-GTraits-Postcard-Classes';
		package: 'Lands-MOODs';
		package: 'Lands-MOODs-Geo';
		package: 'Lands-Lise-GTraits';
		package: 'Lands-Lise';
		package: 'Lands-Lise-Playground';
		package: 'Lands-UI';
		package: 'Lands-Book'