baselines
baseline: spec
	<baseline>
	spec
		for: #common
		do: [ spec
				package: 'Lands-MOGs-Gray-Lexing';
				package: 'Lands-MOGs-Gray';
				package: 'Lands-ToolCompatibility';
				package: 'Lands-Parsers';
				package: 'Lands-LanguageClasses';
				package: 'Lands-GTraits';
				package: 'Lands-GTraits-Parsers';
				package: 'Lands-GTraits-Postcard-Classes';
				package: 'Lands-MOODs';
				package: 'Lands-MOODs-Epi';
				package: 'Lands-MOODSs-Geo';
				"package: 'Lands-MOODs-Targets';"
				package: 'Lands-Lise-GTraits';
				package: 'Lands-Lise' ]