as yet unclassified
altPostcard: x

  'altPostcard(x): "remember to include the signature
	 	<menu: 3 priority: #''-34''>
    	var y := #[100] + self.bSize() + super.bSize().
	 	var d := Dictionary.new().
    	if true & false.not() & nil.isNil() { 
			var inter := {$a. #a class. -4e-2. -10r2. 3s2}.intersetion(#($b b -0.04 -2 3))
				.groupedBy(f(i){i.class()},having=f(group){group.size() > 1}).
			var step := f(i) { y := y + i }.
			while(x + y.first() < 255) step(x). "notice the single statement style here"
    		for item in inter do: { 
        		var t := item.class().name().
		  		d[t] := item.
        		Transcript.show(t);show('' '');show(item);show('' '')
	 		}
	 	} else { self.halt() } 
    	return x < y.first()'