as yet unclassified
funcInvVarImpDeclForFBlockReturnWhileIfPostcard

	^ 'postcard(x):
	<menu: 3 priority: #''-34''>
  	var y :=  #[100] + self bSize + super bSize.
	var d := Dictionary new.
   if true & false not & nil isNil {   
		var inter := ({$a. #a class. -4e-2. -10r2. 3s2} intersection: #($b b -0.04 -2 3))
			groupedBy: [ :i | i class ] having: [ :group | group size > 1 ].
		var step := f(i) { y := y + i }.
		while y first + x < 255. step(x).
		for item in inter do: { 
			var t := item class name.
			d at: t put: item. 
         Transcript show: t; show: '' ''; show: item; show: '' ''
		}
	} else self halt.
	return x < y first'