as yet unclassified
Geranium

	StatScenario Geranium {
   		coordinates = S 46.16352961038194, 
		              W -1.1302614212036133, 
		              N 46.166851083597415,
                    E -1.1267745494842527
   		sum(buildings) = 46
   		sum(residences) = 186 
   		stats(residences) = 6.52% SmallRenovatedHlmBlock, 
        	                 8.965% LargeRenovatedHlmBlock,
                          4.34% SmallNewHlmBlock,
                          2.17% LargeNewHlmBlock,
                          23.91% HLMHousing,
                          19.56% SocialHousing,
                          34.54% PrivateHousing
    	climate = LaRochelleAverage
    	trends = FrenchConsumptionTrends
    	weights = EmpiricalHypothesis
    	time(simulation) = 1 year 
	}