accessing
contents

^ contents ifNil: [contents := 
				
		'Lands' -> { 
	 
		'*Introduction' -> {  
			'Lan.d.s: Introduction' -> {  } @ 'project'.
			'Languages are Everywhere' -> {  } @ 'project'.
			'They Are All Around You' -> {  } @ 'project'.
			'Our Linguistic Future' -> {  } @ 'project'.
			'The Lan.d.s Project' -> {  } @ 'project'.
		} @ 'dragon_L_White'. 
	
		'*Gray and ASL' -> {  
			'MOGs, Gray & ASL' -> {  } @ 'project'.
			'Expression Explorations' -> {  
				'Grammar REPL' -> {  } @ 'repl'. 
				'OO Design' -> {  
					'Expression MOG' -> {  } @ 'class'.
					'Expression ASL' -> {  } @ 'class'.
				} @ 'project'
			} @ 'project'.
			'The Calc Language' -> {  
				'OO REPL' -> {  } @ 'repl'.
				'Grammar' -> {  } @ 'class'.
				'Evaluator' -> {  } @ 'class'
			} @ 'project'.
			"'ASL Postcards' -> {  
			} @ 'project'."
			'Multi-ordered Pharo' -> {  
				'Pharo REPL' -> { } @ 'repl'.
				'Postcard' -> {  } @ 'class'.
				'MsgSend Rule' -> {  } @ 'class'.
				'Message Rule' -> {  } @ 'class'.
				'MsgSend Action' -> {  } @ 'class'.
			} @ 'project'
		} @ 'gray'.
	
		'*GrammarTraits' -> {  
			'GTraits Overview' -> {  } @ 'project'.
			'GTraits Grammar' -> {  } @ 'project'.
			'GTraits ASL Actions' -> {  } @ 'project'.
			'Pharo GTraits Recognizer'-> {  } @ 'project'.
			'Pharo GTraits Parser'-> {  } @ 'project'.
			'GTraits Postcard' -> {  } @ 'project'.	
			'Pharo Extentions' -> {  
				'Extending Pharo' -> {  } @ 'project'.
				'Alternative Mixed Postcard' -> {  } @ 'class'.
				'Alternative Postcard' -> {  } @ 'class'.
				'Testing Postcards' -> {  } @ 'class'.
				'Extended Grammar' -> {  } @ 'class'.
				'Extended Actions' -> {  } @ 'class'
			} @ 'project'.
		} @ 'grammarTraits'.	
			
		'*MOODs' -> {  
			'MOODs Raison d'' etre' -> {  } @ 'project'.
			'Modeling and Parsing' -> {  } @ 'project'.
			'Example: GeoScripter' -> {  
			} @ 'project'.
			'GeoDomain' -> {  } @ 'project'.
			'GeoModeler' -> {  } @ 'project'.
			"'Beyond the Workbench' -> {  } @ 'project'"
			"co-existance of DSLs and dialects in the same run-time !!!"
		} @ 'moods'.
		
		'*Lise' -> {  
			'Xerox+SICP+Bell labs' -> {  } @ 'project'.
			'Emergent Semantics' -> {  } @ 'project'.
			'The Lise Postcard' -> {  } @ 'project'.
			'Test Norvig' -> {  } @ 'project'.
			'The Alt-Lise Postcard' -> {  } @ 'project'.
			'The Alt-Mixed Lise Postcard'	-> {  } @ 'project'.
			'Sharing Primary Values' -> {  } @ 'project'.
			'The Lise Grammar' -> {  } @ 'project'.
			'The Lise Compiler' -> {  } @ 'project'
		} @ 'lise'.
		
		'*Book' -> {  
			'Theory & App. of MOGs' -> {  } @ 'project'.
			'TOC and Support' -> {  } @ 'project'.
			'Patreon Tiers' -> {  } @ 'project'.
		} @ 'landsBook'.
		
		'*Lectures' -> {  
			'The Lan.d.s Lectures' -> {  } @ 'project'.
			'Lectures: Days 1 to 6' -> {  } @ 'project'.
		} @ 'lectures'.
		
	}

]