accessing
contents

^ contents ifNil: [contents := 
				
		'Lands' -> { 
	 
		'*Introduction' -> {  
			'Languages are Everywhere' -> {  } @ 'project'.
			'Languages are the Future' -> {  } @ 'project'.
			'Chomsky and Ford' -> {  } @ 'project'.
			'Multi-ordered Grammars' -> {  } @ 'project'.
			'The Lan.d.s Project' -> {  } @ 'project'.
		} @ 'dragon_L_White'. 
	
		'*Gray and ASL' -> {  
			'Expression Explorations' -> {  
				'Grammar REPL' -> {  } @ 'repl'. 
				'OO Design' -> {  
					'Expression MOG' -> {  } @ 'class'.
					'Expression ASL' -> {  } @ 'class'.
				} @ 'project'
			} @ 'project'.
			'The Calc Language' -> {  
				'OO REPL' -> {  } @ 'repl'.
				'Grammar' -> {  } @ 'class'.
				'Evaluator' -> {  } @ 'class'
			} @ 'project'.
			"'ASL Postcards' -> {  
			} @ 'project'."
			'Multi-ordered Pharo' -> {  
				'Pharo REPL' -> { } @ 'repl'.
				'Postcard' -> {  } @ 'class'.
				'MsgSend Rule' -> {  } @ 'class'.
				'Message Rule' -> {  } @ 'class'.
				'MsgSend Action' -> {  } @ 'class'.
			} @ 'project'
		} @ 'gray'.
	
		'*GrammarTraits' -> {  
			'GTraits Overview' -> {  } @ 'project'.
			'GTraits Grammar' -> {  } @ 'project'.
			'GTraits ASL Actions' -> {  } @ 'project'.
			'Pharo GTraits Recognizer'-> {  } @ 'project'.
			'Pharo GTraits Parser'-> {  } @ 'project'.
			'GTraits Postcard' -> {  } @ 'project'.	
			'Pharo Extentions' -> {  
				'Extending Pharo' -> {  } @ 'project'.
				'Alternative Mixed Postcard' -> {  } @ 'class'.
				'Alternative Postcard' -> {  } @ 'class'.
				'Testing Postcards' -> {  } @ 'class'.
				'Extended Grammar' -> {  } @ 'class'.
				'Extended Actions' -> {  } @ 'class'
			} @ 'project'.
		} @ 'grammarTraits'.	
			
		'*MOODs' -> {  
			'MOODs Raison d'' etre' -> {  } @ 'project'.
			'Example: GeoScripter' -> {  
			} @ 'project'.
			'GeoDomain' -> {  } @ 'project'.
			'GeoModeler' -> {  } @ 'project'.
			'Beyond the Workbench' -> {  } @ 'project'
			"co-existance of DSLs and dialects in the same run-time !!!"
		} @ 'moods'.
		
		'*Lise' -> {  
			'Xerox+SICP+Bell labs' -> {  } @ 'project'.
			'The Lise Postcard' -> {  } @ 'project'.
			'Test Norvig' -> {  } @ 'project'.
			'The Alt-Lise Postcard' -> {  } @ 'project'.
			'The Alt-Mixed Lise Postcard'	-> {  } @ 'project'.
			'Sharing Primary Values' -> {  } @ 'project'.
			'The Lise Grammar' -> {  } @ 'project'.
			'The Lise Compiler' -> {  } @ 'project'
		} @ 'lise'.
		
		'*Book' -> {  
			'Chapter 1' -> {  } @ 'project'.
			'Chapter 2' -> {  } @ 'project'.
			'Chapter 3' -> {  } @ 'project'.
			'Chapter 4' -> {  } @ 'project'.
			'Chapter 5' -> {  } @ 'project'.
			'Chapter 6' -> {  } @ 'project'.
			'Patreon' -> {  } @ 'project'.
			'TOC-Board' -> {  } @ 'project'
		} @ 'landsBook'.
		
		'*Lectures' -> {  
			'Day 1' -> {  } @ 'project'.
			'Day 2' -> {  } @ 'project'.
			'Day 3' -> {  } @ 'project'.
			'Day 4' -> {  } @ 'project'.
			'Day 5' -> {  } @ 'project'.
			'Day 6' -> {  } @ 'project'.
		} @ 'lectures'.
		
	}

]