accessing
"protocol: accessing"
unaryOp

	^ super unaryOp ==> {
		[ :tokens | tokens first staro ]. 
		[ :tokens | tokens first staro ]."staro" "concrete examples of difference"
		[ :tokens | tokens first pluso ].
		[ :tokens | tokens first pluso ]."pluso ?" "concerte example of difference"
		[ :tokens | tokens first opto ].
		[ :tokens | tokens first opto ]."opto" "concrete example of difference"
		[ :tokens | tokens second and ].
		[ :tokens | tokens second not ]
	}. 