as yet unclassified
altPostcard(x): 

	 	<menu: 3 priority: #'-34'>
    	var y := #[100] + self.bSize() + super.bSize().
	 	var d := Dictionary.new().
    	if true & false.not() & nil.isNil() { 
			var inter := {$a. #a class. -4e-2. -10r2. 3s2}.intersection(#($b b -0.04 -2 3))
			.groupedBy(f(i){i.class()}.having=f(group){group.size() > 1}).
			var step := f(i) { y := y + i }.
			while y.first() + x < 255. step(x).
    		for item in inter do: { 
        		var t := item.class().name().
				t := t[1::t.size()-1].
		  		d[t] := item.
        		Transcript.show(t);.show(' ');.show(item);.show(' ')
	 		}
	 	} else self.halt(). 
    	return x < y.first()